# Generated by Django 3.1.2 on 2020-10-29 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestorDeProductos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Producto',
            new_name='Mercaderia',
        ),
    ]
