# Generated by Django 3.1.2 on 2020-10-30 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestorDeProductos', '0003_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.IntegerField()),
                ('fecha', models.DateField()),
                ('email', models.EmailField(max_length=400)),
                ('totalCompra', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=50)),
                ('activo', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoBarra', models.DecimalField(decimal_places=0, max_digits=13)),
                ('nombre', models.TextField()),
                ('email', models.TextField()),
                ('fechaNacimiento', models.DateField()),
                ('telefono', models.TextField()),
                ('region', models.TextField()),
                ('comuna', models.TextField()),
                ('nivelEducacional', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Boleta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idProducto', models.IntegerField()),
                ('idBoleta', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('precioVenta', models.IntegerField()),
                ('subtotal', models.IntegerField()),
                ('boleta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestorDeProductos.boleta')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.DecimalField(decimal_places=0, max_digits=13)),
                ('descripcion', models.TextField()),
                ('stock', models.IntegerField()),
                ('precioCosto', models.IntegerField()),
                ('precioVenta', models.IntegerField()),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestorDeProductos.categoria')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestorDeProductos.marca')),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=50)),
                ('direccion', models.TextField(max_length=50)),
                ('telefono', models.TextField(max_length=50)),
                ('encargado', models.TextField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Mercaderia',
        ),
        migrations.AddField(
            model_name='boleta',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestorDeProductos.cliente'),
        ),
        migrations.AddField(
            model_name='boleta',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestorDeProductos.producto'),
        ),
        migrations.AddField(
            model_name='boleta',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestorDeProductos.sucursal'),
        ),
    ]
