# Generated by Django 3.1.2 on 2020-10-30 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestorDeProductos', '0004_auto_20201030_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='codigoBarra',
        ),
        migrations.AddField(
            model_name='cliente',
            name='run',
            field=models.TextField(default=111111111, max_length=12),
            preserve_default=False,
        ),
    ]
