# Generated by Django 3.1.2 on 2020-11-05 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestorDeProductos', '0005_auto_20201030_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='folio',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='activo',
            field=models.BooleanField(max_length=50),
        ),
        migrations.AlterField(
            model_name='detalle_boleta',
            name='idProducto',
            field=models.TextField(),
        ),
    ]
